NewStore/Models/Compra.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using NewStore.Areas;
using System.ComponentModel.DataAnnotations;

namespace NewStore.Models
{
    //Classe para BD
    public class Compra
    {
        [Key]
        public Guid Id { get; set; }

        public string UserID { get; set; }
    
        public int ProductID { get; set; }

        public DateTime DtCompra { get; set; }

        public bool Finalized { get; set; }
    }
}

NewStore/Models/CompraViewModel.cs
using NewStore.Areas.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewStore.Models
{
    //Modelo para as telas de listagem de compras
    public class CompraViewModel
    {
        public string UserName{ get; set; }
        public List<ProdutoCompraView> ComprasProdutos { get; set; }
        public string ErrorMessage { get; set; }
    }
}

NewStore/Controllers/ComprasController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NewStore.Areas.Identity;
using NewStore.Data;
using NewStore.Models;

namespace NewStore.Controllers
{
    [Authorize]
    public class ComprasController : Controller
    {
        //Injeção de classe de BD
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ComprasController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }        

        //Ao finalizar a operação de compra
        [HttpPost]
        public async Task<IActionResult> FinalizarCompra(CompraViewModel model)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            float precoFinal = 0;            
            
            foreach (ProdutoCompraView pcv in model.ComprasProdutos)
            {
                //Soma os preçoc dos produtos do carrinho
                precoFinal += pcv.Produto.Price;
                var compraId = pcv.CompraProd.Id;
                var compra = await _context.Compras.FindAsync(compraId);

                //Atualiza os produtos do banco de dados para efetivar as compras
                compra.Finalized = true;
                compra.DtCompra = DateTime.Now;
                _context.Update(compra);
            }

            if(precoFinal > currentUser.Cash)
            {
                //Compra não autorizada, saldo insuficiente, Recarrega a página com mensagem de erro
                model.ErrorMessage = "Saldo insuficiente para finalizar a compra.";
                return View("CompraView", model);
            }
            else
            {
                //Compra aprovada, salva modificações do banco, abre tela de historico de compras
                currentUser.Cash -= precoFinal;
                await _userManager.UpdateAsync(currentUser);
                await _context.SaveChangesAsync();

                return RedirectToAction("Historico");
            }

        }
        
        public async Task<IActionResult> Historico()
        {
            var currentUser = await _userManager.GetUserAsync(User);

            //Carrega lista de compras que já foram aprovados na compra daquele cliente
            var comprasFinalizadas = await _context.Compras
               .Where(x => x.Finalized == true && x.UserID == currentUser.Id)
               .ToArrayAsync();

            List<ProdutoCompraView> prods = new List<ProdutoCompraView>();

            //Encontra produto correspondente ao codigo dele na compra
            foreach (Compra c in comprasFinalizadas)
            {
                var temp = await _context.Products
                    .Where(x => x.ProductID == c.ProductID)
                    .SingleOrDefaultAsync();
                prods.Add(
                    new ProdutoCompraView
                    {
                        Produto = temp,
                        CompraProd = c
                    });
            }

            //Monta obj para View
            var compraVM = new CompraViewModel
            {
                ComprasProdutos = prods,
                UserName = currentUser.Name
            };

            return View(compraVM);
        }

        //Tela de carrinho
        public async Task<IActionResult> CompraView(int? id)
        {
            var currentUser = await _userManager.GetUserAsync(User);

            //Se possuir id adiciona na lista de compras não finalizadas do cliente
            if (id != null)
            {

               var product = await _context.Products
                    .FirstOrDefaultAsync(m => m.ProductID == id);
                if (product == null)
                {
                    return NotFound();
                }
                await AddCompraCart(currentUser, product);
            }

            //Obtem lista de compras não finalizadas do cliente
            var comprasUserCart = await _context.Compras
                .Where(x => x.Finalized == false && x.UserID == currentUser.Id)
                .ToArrayAsync();

           List<ProdutoCompraView> prods = new List<ProdutoCompraView>();

            //Encontra produto correspondente ao codigo dele na compra
            foreach (Compra c in comprasUserCart)
            {
                var temp = await _context.Products
                    .Where(x => x.ProductID == c.ProductID)
                    .SingleOrDefaultAsync();
                prods.Add(
                    new ProdutoCompraView
                    {
                        Produto = temp,
                        CompraProd = c
                    });
            }

            //Monta obj para View
            var compraVM = new CompraViewModel
            {
                ComprasProdutos = prods,
                UserName = currentUser.Name
            };

            return View(compraVM);
        }

        public async Task<IActionResult> RemoveCompra(Guid id)
        {
           //Remove compra do carrinho
            var compra = await _context.Compras.FindAsync(id);
            _context.Compras.Remove(compra);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(CompraView));
            
        }

        //Adiciona compra no carrinho
        public async Task<bool> AddCompraCart(AppUser currentUser, Product prod)
        {
            Compra compraCart = new Compra
            {
                ProductID = prod.ProductID,
                UserID = currentUser.Id,
                Id = new Guid(),
                Finalized = false
            };
            _context.Compras.Add(compraCart);

            var saveResult = await _context.SaveChangesAsync();
            return saveResult == 1;
        }

    }
}

NewStore/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Rewrite;
using Microsoft.EntityFrameworkCore;
using NewStore.Areas.Identity;
using NewStore.Data;
using NewStore.Models;

namespace NewStore.Controllers
{
    
    public class ProductsController : Controller
    {
        //private readonly IProductServices _productServices;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<AppUser> _userManager;

        public ProductsController(ApplicationDbContext context, UserManager<AppUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> ProductHome()
        {
            //var products = await _productServices.GetIncompleteProductAsync();
            var products = await _context.Products.ToArrayAsync();
            
            var pv = new ProductViewModel
            {
                Products = products
            };
            return View(pv);
        }


        // GET: Products
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Products/Details/5
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductID,Name,Price,Description,UrlImage")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ProductID,Name,Price,Description,UrlImage")] Product product)
        {
            if (id != product.ProductID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .FirstOrDefaultAsync(m => m.ProductID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductID == id);
        }
    }
}

NewStore/Views/Compras/CompraView.cshtml
@*@using NewStore*@
@model CompraViewModel
@{
    ViewData["Title"] = @"Carrinho de " + Model.UserName;
    
}

<div style="margin-top: 30px;" class="panel panel-default todo-panel">
    <div  class="panel-heading"><p style="font-weight: bold; color: black;">@ViewData["Title"]</p></div>
    @using (Html.BeginForm("FinalizarCompra", "Compras"))
    {
    <form asp-action="PostClick" method="post">        
        <table class="table table-hover">
            @Html.HiddenFor(x => x.UserName)
            <thead>
                @*Se errorMessage tiver conteúdo mostrar na tela*@
                @Html.HiddenFor(x => x.ErrorMessage)
                @if (Model.ErrorMessage != null)
                {
                    <tr>
                        <p style="color: red;">
                            @Html.DisplayFor(x => x.ErrorMessage)
                        </p>
                    </tr>
                }
                <tr>
                    <td style="font-weight: bold;">Produto:</td>
                    <td style="font-weight: bold;">Preço</td>
                    <td> </td>
                </tr>
            </thead>
            @for (int i = 0; i < Model.ComprasProdutos.Count; i++)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(x => x.ComprasProdutos[i].Produto.Name)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].Produto.ProductID)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].Produto.Description)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].Produto.UrlImage)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].Produto.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(x => x.ComprasProdutos[i].Produto.Price)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].Produto.Price)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].CompraProd.ProductID)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].CompraProd.UserID)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].CompraProd.Id)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].CompraProd.DtCompra)
                        @Html.HiddenFor(x => x.ComprasProdutos[i].CompraProd.Finalized)
                    </td>
                    <td>
                        <a asp-controller="Compras" asp-action="RemoveCompra" asp-route-id="@Model.ComprasProdutos[i].CompraProd.Id">Excluir</a>
                    </td>
                </tr>
            }
        </table>
        <input type="submit" value="Finalizar Pedido" class="btn btn-default"  style="float: right; margin: 5px;"/>
        <div style="clear: both"></div>
    </form>
    }
</div>

NewStore/Views/Compras/Historico.cshtml
@model CompraViewModel
@{
    ViewData["Title"] = "Historico";
}

<h2>Historico</h2>


<table class="table table-hover">
    <thead>
        <tr>
            <td style="font-weight: bold;">Produto</td>
            <td style="font-weight: bold;">Preço</td>
            <td style="font-weight: bold;">Descrição</td>
            <td style="font-weight: bold;">Data</td>
            <td></td>
        </tr>
    </thead>
    @foreach (var item in Model.ComprasProdutos)
        {
    <tr>
        <td>@item.Produto.Name</td>
        <td>@item.Produto.Price</td>
        <td>@item.Produto.Description</td>
        <td>@item.CompraProd.DtCompra</td>
        <td><div class="button"><a asp-action="Details" asp-controller="Products" asp-route-id="@item.Produto.ProductID">Detalhes</a></div></td>
    </tr>
        }
        
</table>